import Head from 'next/head'
import Layouts from '../components/layouts'
import Card from '../components/card'
import Link from 'next/link'

export default function Home({ pokemons }) {
  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <div className='space-y-4'>
          <div className='flex items-center justify-between py-8'>
            <div></div>
            <h1 className='text-center text-4xl font-bold'>Pokemon App</h1>
            <div></div>
          </div>
          <input type="text" className='w-full p-4 rounded-lg' placeholder='Search Pokemon...' />
          {pokemons.results.map((pokemon, index) => (
            <Card key={index}>
              <Link href={`/pokemon?id=${index + 1}`}>
                <div className='px-8 py-4 flex space-x-4 items-center justify-start'>
                  <img className='w-24 h-auto' src={'https://assets.pokemon.com/assets/cms2/img/pokedex/full/' + ("00" + (index + 1)).slice(-3) + '.png'} />
                  <p className='text-gray-600 uppercase text-2xl font-bold'>{pokemon.name}</p>
                </div>
              </Link>
            </Card>
          ))}
        </div>
      </Layouts>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const res = await fetch('https://pokeapi.co/api/v2/pokemon')
    const pokemons = await res.json()
    return {
      props: {
        pokemons,
      },
    }
  } catch (error) {
    console.log(error)
  }
  return {
    notFound: true
  }
}